language: node_js

node_js:
  - "node"

git:
  depth: 3

before_deploy:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"

deploy:
  provider: script
  script: scripts/ci-deploy.sh
  on:
    branch: master
