#!/bin/bash

if [ $TRAVIS_SECURE_ENV_VARS == "true" ] && [[ -z $GH_TOKEN ]]; then
  cd ../.. || exit
  mkdir gh-pages
  cd gh-pages || exit
  git clone --depth=1 --branch=gh-pages "https://github.com/${TRAVIS_REPO_SLUG}.git"
  cd aria-practices || exit
  curl "https://labs.w3.org/spec-generator/?type=respec&url=https://rawgit.com/${TRAVIS_REPO_SLUG}/master/aria-practices.html" -o index.html -f --retry 3
  cp -r "../../${TRAVIS_REPO_SLUG}/examples" .

  git add .
  git commit -m "Generated by TRAVIS-CI"
  git push "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" gh-pages > /dev/null 2>&1
else
  echo 'GH_TOKEN is not available, please define it by following https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings'
  exit 1
fi
